version: '3.7'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - type: volume
        source: elastic-vol
        target: /usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: 192.168.99.100
      ELASTICSEARCH_URL: http://192.168.99.100:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
    volumes:
      - type: volume
        source: kibana-vol
        target: /data
volumes:
  kibana-vol:
  elastic-vol:
